version: "3.8"

services:
  go-api:
    build:
      context: ./docker/go-api
      dockerfile: ./docker/go-api/Dockerfile
    image: go-api:latest
    container_name: gin-rush-go
    restart: unless-stopped
    command: go run
    depends_on:
      - mysql
    networks:
      - internal

  mysql:
    build:
      context: ./docker/mysql
      build: .