version: "3.8"

services:
  go-api:
    build:
      context: ./
      dockerfile: ./docker/go-api/Dockerfile
    image: rush-api:latest
    container_name: gin-rush-go
    volumes:
      - ./logs:/logs
    depends_on:
      - db
      - redis
      - rabbitmq
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - internal

  db:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    image: rush-db:latest
    container_name: gin-rush-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    platform: linux/x86_64
    networks:
      - internal

  redis:
    image: bitnami/redis:latest
    container_name: gin-rush-redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/bitnami/redis/data
    restart: always
    networks:
      - internal

  rabbitmq:
    build:
      context: ./docker/rabbitmq
      dockerfile: Dockerfile
      args:
        - RABBITMQ_USER=${RABBITMQ_USER}
        - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    image: rush-rabbitmq:latest
    container_name: gin-rush-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - internal

volumes:
  mysql-data:
  redis-data:
  rabbitmq-data:

networks:
  internal:
    driver: bridge