version: "3.8"

services:
  go-api:
    build:
      context: ./
      dockerfile: ./docker/go-api/Dockerfile
    image: go-api:latest
    container_name: gin-rush-go
    env_file:
      - ./.env
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      - internal

networks:
  internal:
    driver: bridge