version: "3.8"

services:
  go-api:
    build:
      context: ./
      dockerfile: ./docker/go-api/Dockerfile
    image: rush-api:latest
    container_name: gin-rush-go
    environment:
      - DB_HOST=gin-rush-mysql
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - ./logs:/logs
    depends_on:
      - db
      - redis
      - rabbitmq
    ports:
      - "8080:8080"
    networks:
      - internal

  db:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    image: rush-db:latest
    container_name: gin-rush-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    platform: linux/x86_64
    networks:
      - internal

  redis:
    image: redis:latest
    container_name: gin-rush-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - internal

  rabbitmq:
    image: rabbitmq:latest
    container_name: gin-rush-broker
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - broker-data:/var/lib/broker
    networks:
      - internal

volumes:
  mysql-data:
  redis-data:
  broker-data:

networks:
  internal:
    driver: bridge