name: gin-rush
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
jobs:
  build:
    name: Docker environment run
    strategy:
      matrix:
        go-version: [ 1.16.6 ]
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    env:
      ROLLBAR_TOKEN: ${{ secrets.ROLLBAR_TOKEN }}
      ROLLBAR_ENV_MODE: production
      DB_ROOT_PASS: ${{ secrets.DB_ROOT_PASS }}
      DB_HOST: db
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASSWORD }}
      DB_DATABASE: gin-rush
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Docker-Compose
        run: docker-compose up -d